arch:
- aarch64
- amd64
- armv7
backup_exclude:
- node_modules
description: Homebridge - HomeKit support for the impatient
host_network: true
image: homebridge/homebridge
init: false



host_network: true
host_dbus: true                # map host D-Bus into the add-on
udev: true
usb: true                      # if you use a USB BT dongle
privileged:
  - NET_RAW
  - NET_ADMIN
devices:
  - /dev/hci0                  # OR map the whole USB bus: /dev/bus/usb
environment:
  ENABLE_AVAHI: "0"


map:
- path: /homebridge
  read_only: false
  type: addon_config
name: Homebridge
panel_icon: mdi:bridge
ports:
  8581/tcp: 8581
ports_description:
  8581/tcp: Homebridge UI
slug: homebridge
url: https://hub.docker.com/r/homebridge/homebridge
version: '2025-08-20'
webui: http://[HOST]:[PORT:8581]
